#!/bin/bash
# Valida si el numero ingresado es primo

echo "Ingrese un numero"
read numero
divisor=$numero
bandera=1
for i in $(seq 1 $divisor)
do
	if (( numero % i == 0 && i != 1 && i != numero || numero == 1)); then
		echo "No es primo"
		bandera=0
		break
	fi
done
if (( bandera == 1 )); then
	echo "Es primo"
fi
